### Exploring Staple Food Price Dataset

In [1]:
import pandas as pd
# Load the dataset
df = pd.read_csv('data/raw/ethiopian_agriculture/02_staple_food_price.csv')
df.head()

,country,market,admin_1,longitude,latitude,cpcv2,product,source_document,period_date,price_type,product_source,unit,unit_type,currency,value,Unnamed: 15
0,Ethiopia,"Addis Ababa, Merkato",Addis Ababa,38.7667,9.03333,R01701BD,Beans (Haricot),Famine Early Warning Systems Network (FEWS NET...,2020-01-01,Retail,Local,kg,Weight,ETB,41.0,NaN
1,Ethiopia,"Addis Ababa, Merkato",Addis Ababa,38.7667,9.03333,R01701BD,Beans (Haricot),Famine Early Warning Systems Network (FEWS NET...,2020-01-08,Retail,Local,kg,Weight,ETB,46.0,NaN
2,Ethiopia,"Addis Ababa, Merkato",Addis Ababa,38.7667,9.03333,R01701BD,Beans (Haricot),Famine Early Warning Systems Network (FEWS NET...,2020-01-15,Retail,Local,kg,Weight,ETB,48.6,NaN
3,Ethiopia,"Addis Ababa, Merkato",Addis Ababa,38.7667,9.03333,R01701BD,Beans (Haricot),Famine Early Warning Systems Network (FEWS NET...,2020-01-22,Retail,Local,kg,Weight,ETB,49.0,NaN
4,Ethiopia,"Addis Ababa, Merkato",Addis Ababa,38.7667,9.03333,R01701BD,Beans (Haricot),Famine Early Warning Systems Network (FEWS NET...,2020-01-29,Retail,Local,kg,Weight,ETB,50.0,NaN

In [2]:
df.tail()

,country,market,admin_1,longitude,latitude,cpcv2,product,source_document,period_date,price_type,product_source,unit,unit_type,currency,value,Unnamed: 15
77012,Ethiopia,Yabelo,Oromia,38.0934,4.89343,R01112AA,Wheat Grain,Famine Early Warning Systems Network (FEWS NET...,2023-05-24,Retail,Local,kg,Weight,ETB,61.482,NaN
77013,Ethiopia,Yabelo,Oromia,38.0934,4.89343,R01112AA,Wheat Grain,Famine Early Warning Systems Network (FEWS NET...,2023-05-31,Retail,Local,kg,Weight,ETB,62.310,NaN
77014,Ethiopia,Yabelo,Oromia,38.0934,4.89343,R01112AA,Wheat Grain,Famine Early Warning Systems Network (FEWS NET...,2023-06-07,Retail,Local,kg,Weight,ETB,58.368,NaN
77015,Ethiopia,Yabelo,Oromia,38.0934,4.89343,R01112AA,Wheat Grain,Famine Early Warning Systems Network (FEWS NET...,2023-06-14,Retail,Local,kg,Weight,ETB,57.138,NaN
77016,Ethiopia,Yabelo,Oromia,38.0934,4.89343,R01112AA,Wheat Grain,Famine Early Warning Systems Network (FEWS NET...,2023-06-21,Retail,Local,kg,Weight,ETB,51.930,NaN

In [3]:
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

Shape: (77017, 16)

Columns:
['country', 'market', 'admin_1', 'longitude', 'latitude', 'cpcv2', 'product', 'source_document', 'period_date', 'price_type', 'product_source', 'unit', 'unit_type', 'currency', 'value', 'Unnamed: 15']

Data Types:
country                str
market                 str
admin_1                str
longitude          float64
latitude           float64
cpcv2                  str
product                str
source_document        str
period_date            str
price_type             str
product_source         str
unit                   str
unit_type              str
currency               str
value              float64
Unnamed: 15        float64
dtype: object

Missing Values:
country                0
market                 0
admin_1                0
longitude              0
latitude               0
cpcv2                  0
product                0
source_document        0
period_date            0
price_type             0
product_source         0
unit                   0
unit_type              0
currency               0
value              20645
Unnamed: 15        77017
dtype: int64

Duplicate Rows:
0

In [4]:
# Convert date to datetime
df["period_date"] = pd.to_datetime(df["period_date"], errors="coerce")

# Check when prices are missing
missing_price = df[df["value"].isna()]

print("Missing prices by year:")
print(missing_price["period_date"].dt.year.value_counts().sort_index())

Missing prices by year:
period_date
2020    4267
2021    6969
2022    7324
2023    2085
Name: count, dtype: int64

In [7]:
missing_price = df[df["value"].isna()]

print("Rows with missing price:", len(missing_price))

display(missing_price.head())

Rows with missing price: 20645

,country,market,admin_1,longitude,latitude,cpcv2,product,source_document,period_date,price_type,product_source,unit,unit_type,currency,value
182,Ethiopia,"Addis Ababa, Merkato",Addis Ababa,38.7667,9.03333,L02121AB,Camels (Local Quality),Famine Early Warning Systems Network (FEWS NET...,2020-01-01,Retail,Local,ea,Item,ETB,NaN
183,Ethiopia,"Addis Ababa, Merkato",Addis Ababa,38.7667,9.03333,L02121AB,Camels (Local Quality),Famine Early Warning Systems Network (FEWS NET...,2020-01-08,Retail,Local,ea,Item,ETB,NaN
184,Ethiopia,"Addis Ababa, Merkato",Addis Ababa,38.7667,9.03333,L02121AB,Camels (Local Quality),Famine Early Warning Systems Network (FEWS NET...,2020-01-15,Retail,Local,ea,Item,ETB,NaN
185,Ethiopia,"Addis Ababa, Merkato",Addis Ababa,38.7667,9.03333,L02121AB,Camels (Local Quality),Famine Early Warning Systems Network (FEWS NET...,2020-01-22,Retail,Local,ea,Item,ETB,NaN
186,Ethiopia,"Addis Ababa, Merkato",Addis Ababa,38.7667,9.03333,L02121AB,Camels (Local Quality),Famine Early Warning Systems Network (FEWS NET...,2020-01-29,Retail,Local,ea,Item,ETB,NaN

In [5]:
# Check missing prices by product and market
missing_pattern = (
    df[df["value"].isna()]
    .groupby(["market", "product"])
    .size()
    .sort_values(ascending=False)
)

print(missing_pattern.head(20))

market                product
Addis Ababa, Merkato  Camels (Local Quality)    182
Sekota                Beans (Haricot)           182
Sodo                  Wheat Flour               182
                      Camels (Local Quality)    182
Bahir Dar             Camels (Local Quality)    182
Sikela                Oxen (Local Quality)      182
                      Wheat Flour               182
                      Camels (Local Quality)    182
Shashemene            Camels (Local Quality)    182
Nekemte               Wheat Flour               182
Shashemene            Sorghum (Yellow)          182
Sekota                Camels (Local Quality)    182
                      Wheat Flour               182
Nazareth, Adama       Wheat Flour               182
Nekemte               Beans (Haricot)           182
                      Camels (Local Quality)    182
                      Sorghum (Yellow)          182
Warder                Oxen (Local Quality)      182
Chereti               Sorghum (Yellow)          182
Yabelo                Horse beans               182
dtype: int64

In [6]:
missing_summary = (
    df.groupby(["market", "product"])["value"]
      .agg(
          total="size",
          missing="count"
      )
)

missing_summary["missing"] = (
    missing_summary["total"] - missing_summary["missing"]
)

complete_missing = missing_summary[
    missing_summary["missing"] == missing_summary["total"]
]

print("Completely missing market-product combinations:",
      len(complete_missing))

print(complete_missing.head(20))

Completely missing market-product combinations: 45
                                             total  missing
market               product
Addis Ababa, Merkato Camels (Local Quality)    182      182
Awash                Camels (Local Quality)    145      145
                     Oxen (Local Quality)      145      145
Bahir Dar            Camels (Local Quality)    182      182
                     Sorghum (Red)             182      182
                     Sorghum (Yellow)          182      182
Beddenno             Camels (Local Quality)    182      182
Chereti              Mixed Teff                182      182
                     Sorghum (Yellow)          182      182
Degehabour           Mixed Teff                182      182
Dessie               Camels (Local Quality)    182      182
                     Wheat Flour               182      182
Gambella             Camels (Local Quality)    182      182
                     Sorghum (Yellow)          182      182
                     Wheat Flour               182      182
Gode                 Mixed Teff                182      182
                     Sorghum (Yellow)          182      182
Jinka                Camels (Local Quality)    182      182
                     Wheat Flour               182      182
Mekele               Camels (Local Quality)    174      174

In [7]:
# Identify completely missing market-product combinations
missing_summary = (
    df.groupby(["market", "product"])["value"]
      .agg(total="size", available="count")
)

complete_missing = missing_summary[
    missing_summary["available"] == 0
].index

# Remove only those 45 combinations
df = df.set_index(["market", "product"])
df = df.drop(index=complete_missing)
df = df.reset_index()

print("New shape:", df.shape)
print("Remaining missing prices:", df["value"].isna().sum())

New shape: (68978, 16)
Remaining missing prices: 12606

In [8]:
# Check how many missing prices each market-product combination has
partial_missing = (
    df.groupby(["market", "product"])["value"]
      .agg(total="size", available="count")
)

partial_missing["missing"] = (
    partial_missing["total"] - partial_missing["available"]
)

partial_missing = partial_missing[
    partial_missing["missing"] > 0
].sort_values("missing", ascending=False)

print(partial_missing.head(20))

                                         total  available  missing
market            product
Yabelo            Sorghum (Yellow)         182          1      181
Jinka             Sorghum (Yellow)         182          1      181
Gambella          Sorghum (White)          182          1      181
Sodo              Sorghum (Yellow)         182          6      176
Mekele            Beans (Haricot)          174          2      172
Degehabour        Beans (Haricot)          182         11      171
                  Horse beans              182         11      171
Sodo              Sorghum (White)          182         21      161
Beddenno          Sorghum (White)          182         25      157
Sikela            Sorghum (Yellow)         182         27      155
Dire Dawa, Kezira Sorghum (Yellow)         182         29      153
Beddenno          Wheat Flour              182         32      150
Shire             Rice (Milled)            153          9      144
Dire Dawa, Kezira Firewood                 182         43      139
Beddenno          Sorghum (Yellow)         182         44      138
Shire             Sheep (Local Quality)    174         46      128
                  Oxen (Local Quality)     174         46      128
Mekele            Mixed Teff               174         47      127
Shire             Firewood                 174         48      126
                  Wheat Grain              174         49      125

In [9]:
# Calculate percentage of missing prices
partial_missing["missing_pct"] = (
    partial_missing["missing"] / partial_missing["total"] * 100
)

print(partial_missing.head(20))

                                         total  available  missing  \
market            product
Yabelo            Sorghum (Yellow)         182          1      181
Jinka             Sorghum (Yellow)         182          1      181
Gambella          Sorghum (White)          182          1      181
Sodo              Sorghum (Yellow)         182          6      176
Mekele            Beans (Haricot)          174          2      172
Degehabour        Beans (Haricot)          182         11      171
                  Horse beans              182         11      171
Sodo              Sorghum (White)          182         21      161
Beddenno          Sorghum (White)          182         25      157
Sikela            Sorghum (Yellow)         182         27      155
Dire Dawa, Kezira Sorghum (Yellow)         182         29      153
Beddenno          Wheat Flour              182         32      150
Shire             Rice (Milled)            153          9      144
Dire Dawa, Kezira Firewood                 182         43      139
Beddenno          Sorghum (Yellow)         182         44      138
Shire             Sheep (Local Quality)    174         46      128
                  Oxen (Local Quality)     174         46      128
Mekele            Mixed Teff               174         47      127
Shire             Firewood                 174         48      126
                  Wheat Grain              174         49      125

                                         missing_pct
market            product
Yabelo            Sorghum (Yellow)         99.450549
Jinka             Sorghum (Yellow)         99.450549
Gambella          Sorghum (White)          99.450549
Sodo              Sorghum (Yellow)         96.703297
Mekele            Beans (Haricot)          98.850575
Degehabour        Beans (Haricot)          93.956044
                  Horse beans              93.956044
Sodo              Sorghum (White)          88.461538
Beddenno          Sorghum (White)          86.263736
Sikela            Sorghum (Yellow)         85.164835
Dire Dawa, Kezira Sorghum (Yellow)         84.065934
Beddenno          Wheat Flour              82.417582
Shire             Rice (Milled)            94.117647
Dire Dawa, Kezira Firewood                 76.373626
Beddenno          Sorghum (Yellow)         75.824176
Shire             Sheep (Local Quality)    73.563218
                  Oxen (Local Quality)     73.563218
Mekele            Mixed Teff               72.988506
Shire             Firewood                 72.413793
                  Wheat Grain              71.839080

In [10]:
# Count market-product combinations by missing percentage
summary = partial_missing["missing_pct"]

print("≤ 25% missing:", (summary <= 25).sum())
print("25–50% missing:", ((summary > 25) & (summary <= 50)).sum())
print("50–75% missing:", ((summary > 50) & (summary <= 75)).sum())
print("> 75% missing:", (summary > 75).sum())

≤ 25% missing: 208
25–50% missing: 30
50–75% missing: 46
> 75% missing: 27

In [11]:
print("Total market-product series:", len(partial_missing))

print("≤ 50% missing:",
      (partial_missing["missing_pct"] <= 50).sum())

print("> 50% missing:",
      (partial_missing["missing_pct"] > 50).sum())

print("Total rows before filtering:", len(df))

# Rows belonging to series with ≤50% missing
keep_series = partial_missing[
    partial_missing["missing_pct"] <= 50
].index

filtered_df = df.set_index(["market", "product"])
filtered_df = filtered_df.loc[filtered_df.index.isin(keep_series)]
filtered_df = filtered_df.reset_index()

print("Rows after filtering:", len(filtered_df))

Total market-product series: 311
≤ 50% missing: 238
> 50% missing: 73
Total rows before filtering: 68978
Rows after filtering: 41608

In [12]:
# Keep only market-product combinations with ≤50% missing
keep_series = partial_missing[
    partial_missing["missing_pct"] <= 50
].index

df = df.set_index(["market", "product"])
df = df.loc[df.index.isin(keep_series)]
df = df.reset_index()

print("New shape:", df.shape)
print("Remaining missing prices:", df["value"].isna().sum())

New shape: (41608, 16)
Remaining missing prices: 3658

In [13]:
# Reload original dataset
df = pd.read_csv(
    'data/raw/ethiopian_agriculture/02_staple_food_price.csv'
)

# Calculate missing percentage for every market-product series
summary = (
    df.groupby(["market", "product"])["value"]
      .agg(total="size", available="count")
)

summary["missing"] = summary["total"] - summary["available"]

summary["missing_pct"] = (
    summary["missing"] / summary["total"] * 100
)

# Keep ALL series with <= 50% missing values
keep_series = summary[
    summary["missing_pct"] <= 50
].index

# Filter dataset
df = (
    df.set_index(["market", "product"])
      .loc[lambda x: x.index.isin(keep_series)]
      .reset_index()
)

print("New shape:", df.shape)
print("Remaining missing prices:", df["value"].isna().sum())

New shape: (56896, 16)
Remaining missing prices: 3658

In [14]:
df["period_date"] = pd.to_datetime(df["period_date"])

missing_by_year = (
    df[df["value"].isna()]
    .groupby(df["period_date"].dt.year)
    .size()
)

print(missing_by_year)

period_date
2020     688
2021    1027
2022    1687
2023     256
dtype: int64

In [15]:
missing_dates = (
    df[df["value"].isna()]
    .groupby(["market", "product"])["period_date"]
    .agg(["min", "max", "count"])
)

print(missing_dates.head(20))

                                                                          min  \
market               product
Addis Ababa, Merkato Refined Vegetable Oil                         2020-05-27
                     Refined sugar                                 2020-05-27
                     Rice (Milled)                                 2020-05-27
Bahir Dar            Beans (Haricot)                               2020-02-12
                     Casual Labor (unskilled, daily, without food) 2020-02-12
                     Diesel                                        2020-01-15
                     Firewood                                      2020-02-12
                     Gasoline                                      2020-02-12
                     Goats (Local Quality)                         2020-02-12
                     Horse beans                                   2020-02-12
                     Maize Grain (White)                           2020-02-12
                     Mixed Teff                                    2020-02-12
                     Oxen (Local Quality)                          2020-02-12
                     Refined Vegetable Oil                         2020-05-27
                     Refined sugar                                 2020-05-27
                     Rice (Milled)                                 2020-05-27
                     Sheep (Local Quality)                         2020-02-12
                     Sorghum (White)                               2020-02-12
                     Wheat Flour                                   2020-01-01
                     Wheat Grain                                   2020-02-12

                                                                          max  \
market               product
Addis Ababa, Merkato Refined Vegetable Oil                         2020-06-03
                     Refined sugar                                 2020-06-03
                     Rice (Milled)                                 2020-06-03
Bahir Dar            Beans (Haricot)                               2020-10-28
                     Casual Labor (unskilled, daily, without food) 2020-09-16
                     Diesel                                        2020-04-08
                     Firewood                                      2020-04-08
                     Gasoline                                      2021-01-06
                     Goats (Local Quality)                         2020-04-08
                     Horse beans                                   2020-10-07
                     Maize Grain (White)                           2020-09-16
                     Mixed Teff                                    2020-09-16
                     Oxen (Local Quality)                          2020-04-15
                     Refined Vegetable Oil                         2020-06-03
                     Refined sugar                                 2020-08-05
                     Rice (Milled)                                 2020-06-03
                     Sheep (Local Quality)                         2020-04-08
                     Sorghum (White)                               2023-06-21
                     Wheat Flour                                   2020-02-12
                     Wheat Grain                                   2020-09-16

                                                                    count
market               product
Addis Ababa, Merkato Refined Vegetable Oil                              2
                     Refined sugar                                      2
                     Rice (Milled)                                      2
Bahir Dar            Beans (Haricot)                                    8
                     Casual Labor (unskilled, daily, without food)      5
                     Diesel                                             3
                     Firewood                                           2
                     Gasoline                                           7
                     Goats (Local Quality)                              2
                     Horse beans                                        3
                     Maize Grain (White)                                2
                     Mixed Teff                                         2
                     Oxen (Local Quality)                               3
                     Refined Vegetable Oil                              2
                     Refined sugar                                     10
                     Rice (Milled)                                      2
                     Sheep (Local Quality)                              2
                     Sorghum (White)                                   60
                     Wheat Flour                                        4
                     Wheat Grain                                        2

In [16]:
# Check consecutive missing values for each market-product series

df = df.sort_values(["market", "product", "period_date"])

df["is_missing"] = df["value"].isna()

gap_info = (
    df.groupby(["market", "product"])["is_missing"]
      .agg(["sum", "max"])
      .sort_values("max", ascending=False)
)

gap_info.columns = ["total_missing", "longest_missing_gap"]

print(gap_info.head(20))

                                                               total_missing  \
market          product
Yabelo          Wheat Grain                                                1
Jinka           Sorghum (Red)                                              1
                Wheat Grain                                                1
Logia           Camels (Local Quality)                                    38
                Casual Labor (unskilled, daily, without food)             32
                Diesel                                                    32
                Gasoline                                                  32
                Goats (Local Quality)                                     32
                Horse beans                                               32
                Maize Grain (White)                                       32
                Mixed Teff                                                32
                Oxen (Local Quality)                                      38
                Refined Vegetable Oil                                     32
                Refined sugar                                             32
                Sheep (Local Quality)                                     34
                Sorghum (White)                                           36
                Sorghum (Yellow)                                          32
                Wheat Flour                                               32
                Wheat Grain                                               32
Nazareth, Adama Beans (Haricot)                                            5

                                                               longest_missing_gap
market          product
Yabelo          Wheat Grain                                                   True
Jinka           Sorghum (Red)                                                 True
                Wheat Grain                                                   True
Logia           Camels (Local Quality)                                        True
                Casual Labor (unskilled, daily, without food)                 True
                Diesel                                                        True
                Gasoline                                                      True
                Goats (Local Quality)                                         True
                Horse beans                                                   True
                Maize Grain (White)                                           True
                Mixed Teff                                                    True
                Oxen (Local Quality)                                          True
                Refined Vegetable Oil                                         True
                Refined sugar                                                 True
                Sheep (Local Quality)                                         True
                Sorghum (White)                                               True
                Sorghum (Yellow)                                              True
                Wheat Flour                                                   True
                Wheat Grain                                                   True
Nazareth, Adama Beans (Haricot)                                               True

In [17]:
def longest_missing_run(s):
    is_missing = s.isna()
    groups = is_missing.ne(is_missing.shift()).cumsum()
    return is_missing.groupby(groups).sum().max()

gap_info = (
    df.groupby(["market", "product"])["value"]
      .agg(
          total_missing=lambda s: s.isna().sum(),
          longest_missing_gap=longest_missing_run
      )
      .sort_values("longest_missing_gap", ascending=False)
)

print(gap_info.head(20))

                                                                 total_missing  \
market            product
Gambella          Sorghum (Red)                                             90
Dire Dawa, Kezira Oxen (Local Quality)                                      53
                  Goats (Local Quality)                                     53
                  Horse beans                                               53
                  Diesel                                                    53
                  Casual Labor (unskilled, daily, without food)             53
                  Camels (Local Quality)                                    59
                  Sorghum (White)                                           53
                  Wheat Flour                                               53
                  Wheat Grain                                               53
                  Sorghum (Red)                                             53
                  Beans (Haricot)                                           53
                  Maize Grain (White)                                       56
                  Gasoline                                                  55
                  Rice (Milled)                                             55
                  Refined sugar                                             55
                  Sheep (Local Quality)                                     53
                  Refined Vegetable Oil                                     55
                  Mixed Teff                                                53
Warder            Wheat Grain                                               86

                                                                 longest_missing_gap
market            product
Gambella          Sorghum (Red)                                                   84
Dire Dawa, Kezira Oxen (Local Quality)                                            53
                  Goats (Local Quality)                                           53
                  Horse beans                                                     53
                  Diesel                                                          53
                  Casual Labor (unskilled, daily, without food)                   53
                  Camels (Local Quality)                                          53
                  Sorghum (White)                                                 53
                  Wheat Flour                                                     53
                  Wheat Grain                                                     53
                  Sorghum (Red)                                                   53
                  Beans (Haricot)                                                 53
                  Maize Grain (White)                                             53
                  Gasoline                                                        53
                  Rice (Milled)                                                   53
                  Refined sugar                                                   53
                  Sheep (Local Quality)                                           53
                  Refined Vegetable Oil                                           53
                  Mixed Teff                                                      53
Warder            Wheat Grain                                                     43

In [18]:
gap_info["gap_category"] = pd.cut(
    gap_info["longest_missing_gap"],
    bins=[0, 5, 20, float("inf")],
    labels=["Short (1-5)", "Medium (6-20)", "Long (>20)"]
)

print(gap_info["gap_category"].value_counts())

gap_category
Short (1-5)      153
Long (>20)        57
Medium (6-20)     28
Name: count, dtype: int64

In [19]:
long_gaps = gap_info[
    gap_info["longest_missing_gap"] > 20
]

print(long_gaps)

                                                                 total_missing  \
market            product
Gambella          Sorghum (Red)                                             90
Dire Dawa, Kezira Oxen (Local Quality)                                      53
                  Goats (Local Quality)                                     53
                  Horse beans                                               53
                  Diesel                                                    53
                  Casual Labor (unskilled, daily, without food)             53
                  Camels (Local Quality)                                    59
                  Sorghum (White)                                           53
                  Wheat Flour                                               53
                  Wheat Grain                                               53
                  Sorghum (Red)                                             53
                  Beans (Haricot)                                           53
                  Maize Grain (White)                                       56
                  Gasoline                                                  55
                  Rice (Milled)                                             55
                  Refined sugar                                             55
                  Sheep (Local Quality)                                     53
                  Refined Vegetable Oil                                     55
                  Mixed Teff                                                53
Warder            Wheat Grain                                               86
Shashemene        Sorghum (White)                                           73
Dessie            Sorghum (Red)                                             84
Sekota            Gasoline                                                  60
Logia             Camels (Local Quality)                                    38
                  Oxen (Local Quality)                                      38
                  Sorghum (White)                                           36
Sekota            Diesel                                                    41
Gode              Horse beans                                               32
Logia             Gasoline                                                  32
                  Goats (Local Quality)                                     32
                  Casual Labor (unskilled, daily, without food)             32
                  Diesel                                                    32
                  Mixed Teff                                                32
                  Wheat Grain                                               32
Sekota            Rice (Milled)                                             64
Logia             Wheat Flour                                               32
                  Sheep (Local Quality)                                     34
                  Refined sugar                                             32
                  Horse beans                                               32
                  Maize Grain (White)                                       32
                  Refined Vegetable Oil                                     32
                  Sorghum (Yellow)                                          32
Sekota            Firewood                                                  34
                  Casual Labor (unskilled, daily, without food)             33
                  Mixed Teff                                                36
                  Sheep (Local Quality)                                     36
                  Sorghum (White)                                           33
                  Refined Vegetable Oil                                     33
                  Sorghum (Red)                                             36
                  Wheat Grain                                               37
                  Maize Grain (White)                                       32
                  Horse beans                                               33
                  Goats (Local Quality)                                     34
                  Oxen (Local Quality)                                      35
Bahir Dar         Sorghum (White)                                           60
Warder            Mixed Teff                                                52
                  Sorghum (Yellow)                                          26

                                                                 longest_missing_gap  \
market            product
Gambella          Sorghum (Red)                                                   84
Dire Dawa, Kezira Oxen (Local Quality)                                            53
                  Goats (Local Quality)                                           53
                  Horse beans                                                     53
                  Diesel                                                          53
                  Casual Labor (unskilled, daily, without food)                   53
                  Camels (Local Quality)                                          53
                  Sorghum (White)                                                 53
                  Wheat Flour                                                     53
                  Wheat Grain                                                     53
                  Sorghum (Red)                                                   53
                  Beans (Haricot)                                                 53
                  Maize Grain (White)                                             53
                  Gasoline                                                        53
                  Rice (Milled)                                                   53
                  Refined sugar                                                   53
                  Sheep (Local Quality)                                           53
                  Refined Vegetable Oil                                           53
                  Mixed Teff                                                      53
Warder            Wheat Grain                                                     43
Shashemene        Sorghum (White)                                                 43
Dessie            Sorghum (Red)                                                   42
Sekota            Gasoline                                                        38
Logia             Camels (Local Quality)                                          37
                  Oxen (Local Quality)                                            37
                  Sorghum (White)                                                 35
Sekota            Diesel                                                          33
Gode              Horse beans                                                     32
Logia             Gasoline                                                        31
                  Goats (Local Quality)                                           31
                  Casual Labor (unskilled, daily, without food)                   31
                  Diesel                                                          31
                  Mixed Teff                                                      31
                  Wheat Grain                                                     31
Sekota            Rice (Milled)                                                   31
Logia             Wheat Flour                                                     31
                  Sheep (Local Quality)                                           31
                  Refined sugar                                                   31
                  Horse beans                                                     31
                  Maize Grain (White)                                             31
                  Refined Vegetable Oil                                           31
                  Sorghum (Yellow)                                                31
Sekota            Firewood                                                        28
                  Casual Labor (unskilled, daily, without food)                   28
                  Mixed Teff                                                      28
                  Sheep (Local Quality)                                           28
                  Sorghum (White)                                                 28
                  Refined Vegetable Oil                                           28
                  Sorghum (Red)                                                   28
                  Wheat Grain                                                     28
                  Maize Grain (White)                                             28
                  Horse beans                                                     28
                  Goats (Local Quality)                                           28
                  Oxen (Local Quality)                                            28
Bahir Dar         Sorghum (White)                                                 27
Warder            Mixed Teff                                                      27
                  Sorghum (Yellow)                                                22

                                                                gap_category
market            product
Gambella          Sorghum (Red)                                   Long (>20)
Dire Dawa, Kezira Oxen (Local Quality)                            Long (>20)
                  Goats (Local Quality)                           Long (>20)
                  Horse beans                                     Long (>20)
                  Diesel                                          Long (>20)
                  Casual Labor (unskilled, daily, without food)   Long (>20)
                  Camels (Local Quality)                          Long (>20)
                  Sorghum (White)                                 Long (>20)
                  Wheat Flour                                     Long (>20)
                  Wheat Grain                                     Long (>20)
                  Sorghum (Red)                                   Long (>20)
                  Beans (Haricot)                                 Long (>20)
                  Maize Grain (White)                             Long (>20)
                  Gasoline                                        Long (>20)
                  Rice (Milled)                                   Long (>20)
                  Refined sugar                                   Long (>20)
                  Sheep (Local Quality)                           Long (>20)
                  Refined Vegetable Oil                           Long (>20)
                  Mixed Teff                                      Long (>20)
Warder            Wheat Grain                                     Long (>20)
Shashemene        Sorghum (White)                                 Long (>20)
Dessie            Sorghum (Red)                                   Long (>20)
Sekota            Gasoline                                        Long (>20)
Logia             Camels (Local Quality)                          Long (>20)
                  Oxen (Local Quality)                            Long (>20)
                  Sorghum (White)                                 Long (>20)
Sekota            Diesel                                          Long (>20)
Gode              Horse beans                                     Long (>20)
Logia             Gasoline                                        Long (>20)
                  Goats (Local Quality)                           Long (>20)
                  Casual Labor (unskilled, daily, without food)   Long (>20)
                  Diesel                                          Long (>20)
                  Mixed Teff                                      Long (>20)
                  Wheat Grain                                     Long (>20)
Sekota            Rice (Milled)                                   Long (>20)
Logia             Wheat Flour                                     Long (>20)
                  Sheep (Local Quality)                           Long (>20)
                  Refined sugar                                   Long (>20)
                  Horse beans                                     Long (>20)
                  Maize Grain (White)                             Long (>20)
                  Refined Vegetable Oil                           Long (>20)
                  Sorghum (Yellow)                                Long (>20)
Sekota            Firewood                                        Long (>20)
                  Casual Labor (unskilled, daily, without food)   Long (>20)
                  Mixed Teff                                      Long (>20)
                  Sheep (Local Quality)                           Long (>20)
                  Sorghum (White)                                 Long (>20)
                  Refined Vegetable Oil                           Long (>20)
                  Sorghum (Red)                                   Long (>20)
                  Wheat Grain                                     Long (>20)
                  Maize Grain (White)                             Long (>20)
                  Horse beans                                     Long (>20)
                  Goats (Local Quality)                           Long (>20)
                  Oxen (Local Quality)                            Long (>20)
Bahir Dar         Sorghum (White)                                 Long (>20)
Warder            Mixed Teff                                      Long (>20)
                  Sorghum (Yellow)                                Long (>20)